name: Deploy Vue3 App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Check package.json
        run: cat package.json

      - name: Install dependencies
        run: |
          npm install
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Show build script
        run: grep '"build"' package.json

      - name: Build with verbose logging
        run: npm run build --verbose
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist